kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/zou2699/demoweb

clone:
  depth: 50


steps:
  - name: backend
    image: golang:1.11
    commands:
      - pwd
      - ls
      - go build
      - go test
      - ls
      - env
  
  - name: publish
    image: plugins/docker
    settings:
      repo: zouhl/demo-app
      auto_tag: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

